[tox]
skipsdist = true
envlist = py{{ cookiecutter.python_version | replace(".", "") }}

[gh-actions]
python =
    {{ cookiecutter.python_version }}: py{{ cookiecutter.python_version | replace(".", "") }}

[testenv]
passenv = PYTHON_VERSION
allowlist_externals = pdm
commands =
    pdm install -v
    pdm run test
    pdm run lint-check

